### ISSUE TITLE
Test Harness not working

### ISSUE THREAD

**Issue by tractorjack** [atariadmin/AtariArcadeSDK#1]
When I try to run index.html in the testharness directory, I get the following errors in Google Chrome (and similar errors in Safari).  OS is Windows Vista 64-bit.   Local webserver is Abyss Web Server.

Error: SyntaxError: Unexpected token ]          Atari.js:70
Uncaught Game Manifest not loaded.         GameShell.js:164

Any ideas why?  Something wrong in "games/GameManifest.json" ?

**Comment by meelash** [comment]
Extra commas on line 19 and 24 of GameManifest.json.

**Comment by tractorjack** [comment]
Thanks meelash.  That solved the problem.  Now I get the following error:

Uncaught TypeError: Cannot read property 'base' of undefined ----------------------  GameShell.js:173

**Comment by tractorjack** [comment]
Found the problem.  In addition, to extra commas on line 19 and 24 of GameManifest.json, line 2 of GameManifest.json should be "mygame" rather than "myGame".
