### ISSUE TITLE
Test Harness not working

### ISSUE THREAD

**Issue by dlayel** [atariadmin/AtariArcadeSDK#5]
Hi everybody, 
when im tryin to run index.html in the testharness directory hi didnt work
hi shows me this message . "Error: Games not loaded."
plzzz help me im lost .

**Comment by lannymcnie** [comment]
Are you running this on a local server? You will need to in order to run this locally.

**Comment by dlayel** [comment]
thnk you the problem is resolved i run it without server :p lol
